version: '3'

services:
  pagonlineteste:
    #image: tomcat:9.0.84-jdk11-corretto
    image: registry-docker.unimedjp.com.br/app-pag-online:latest
    container_name: pagonlineteste
    ports:
      - 8090:8080
    #deploy:
    #  mode: replicated
    #  replicas: 1
    #  placement:
    #    constraints: [node.hostname == cluster-docker-dmz01]
    volumes:
      #PARA NÃO UTILIZAR A IMAGEM DO GIT É NECESSÁRIO DESCOMENTAR E IMAGEM E .WAR ABAIXO##
      #- /opt/storage/pagonline/pagonline.war:/usr/local/tomcat/webapps/pagonline.war
      #- /opt/storage/pagonline/probe/probe.war:/usr/local/tomcat/webapps/probe.war
      #- /opt/storage/pagonline/probe/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      #- /opt/storage/pagonline/server.xml:/usr/local/tomcat/conf/server.xml
      #- /opt/storage/pagonline/setenv.sh:/usr/local/tomcat/bin/setenv.sh
      #- /opt/storage/pagonline/glowroot-agent:/usr/local/glowroot-agent/
      #- /opt/storage/pagonline/ssl/unimedjp.javaks:/opt/ssl/unimedjp.javaks

    restart: always
